### ISSUE TITLE
Compiling the Electron app for other platforms

### ISSUE THREAD

**Issue by GlitchMasta47** [MyRPC/MyRPC#5]
TODO:
- [x] ~~Windows binary~~ Doesn't need to be done, already available (for the most part)
- [x] macOS binary
- [x] Linux binary

**Comment by axelgreavette** [comment]
If you can by all means compile it for whichever you can. I know someone in the Discord server mentioned that they had a Mac they’d be happy to use if they had instruction.

**Comment by GlitchMasta47** [comment]
I'll do Mac packaging first then, and if they don't find they can help test it out (I'm not home and I can't test on my own Mac)

**Comment by RailRunner166** [comment]
well, all you gotta do is clone the repo, install deps, and run `electron-build --mac`

**Comment by RailRunner166** [comment]
i have the mac build configuration written already

**Comment by GlitchMasta47** [comment]
Well I was gonna do it manually but that works too

**Comment by RailRunner166** [comment]
preferably do that, since that uses the ICNS file i made

**Comment by nodatahere** [comment]
What's the build error in Linux? I think I've been able to build it on my system (Xubuntu 18.04 x64). I can share the resulting .appimage if needed.

**Comment by RailRunner166** [comment]
![https://i.railrunner16.me/hAPUYg5.png](https://i.railrunner16.me/hAPUYg5.png) (also in releases)

**Comment by nodatahere** [comment]
Per my edit just now, commit 48ab91a errors out with the attached. Commit c5c742b compiled with apparent success, though appimage integration appears to have some issues.

[error.txt](https://github.com/RailRunner166/MyRPC/files/2719042/error.txt)

**Comment by nodatahere** [comment]
Can't find the linking between the two, but comparing the outputs indicates it does. Building it either way throws out warnings about app categories, but creates an appimage. The appimage throws the following when launched: 
![screenshot_2018-12-31_18-32-54](https://user-images.githubusercontent.com/26449683/50569430-97518380-0d2a-11e9-9a91-4d33d63fe0ef.png)

**Comment by RailRunner166** [comment]
think thonk

**Comment by RailRunner166** [comment]
no idea, tbh

**Comment by RailRunner166** [comment]
maybe make a PR and wait till i merge before running it...

**Comment by nodatahere** [comment]
On further investigation, it looks as though the update mechanism is pitching a fit due to no existing Linux releases. Will investigate further.

**Comment by GlitchMasta47** [comment]
Anybody with a Mac, what error does this app give you? (because I highly doubt that it works)

https://share.dmca.gripe/QaTolwBInwA04yVF.zip

**Comment by nodatahere** [comment]
[Linux build archive](https://drive.google.com/open?id=1SbTBA16Ioif-QE63pWWmSY_fo8FM0xRR)

**Comment by RailRunner166** [comment]
@nodatahere you will need to pull and rebuild usng `yarn make` (preferably) or `npm run make` after installing deps

**Comment by RailRunner166** [comment]
I'm closing this, CI has handled that for us 😄

**Comment by sn8to** [comment]
@kmdrGroch Read this thread again. We were already using electron-builder but there was an issue compiling for other platforms on windows. 

CI has this (mostly) resolved now. I have no idea why I got the email just today.

**Comment by LizAinslie** [comment]
lol, *the app still doesnt work* :^)

**Comment by sn8to** [comment]
that's because you're a Really Good Programmer
